import { Check, Pencil, X } from 'lucide-react';
import { useEffect, useId, useRef, useState } from 'react';

export default function InlineConversationTitle({ title, onSave }: { title: string; onSave: (title: string) => Promise<void> }) {
  const [editing, setEditing] = useState(false); const [value, setValue] = useState(title); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const input = useRef<HTMLInputElement>(null); const id = useId();
  useEffect(() => setValue(title), [title]);
  useEffect(() => { if (editing) { input.current?.focus(); input.current?.select(); } }, [editing]);
  const cancel = () => { setValue(title); setError(''); setEditing(false); };
  const save = async () => { const next = value.trim(); if (!next) { setError('请输入会话名称'); return; } setSaving(true); setError(''); try { await onSave(next); setEditing(false); } catch (e: any) { setError(e?.message || '保存失败，请重试'); } finally { setSaving(false); } };
  if (!editing) return <div className="flex min-w-0 items-center gap-1"><span className="truncate text-sm font-semibold text-text-primary" title={title}>{title}</span><button type="button" aria-label="重命名会话" onClick={() => setEditing(true)} className="ml-1 inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-text-muted transition-colors hover:bg-bg-raised hover:text-text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"><Pencil size={14}/></button></div>;
  return <div className="min-w-0"><label className="sr-only" htmlFor={id}>会话名称</label><div className="flex items-center gap-1"><input id={id} ref={input} value={value} maxLength={120} disabled={saving} onChange={e => setValue(e.target.value)} onBlur={() => { if (!saving && !error) void save(); }} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); void save(); } if (e.key === 'Escape') cancel(); }} className="min-w-0 flex-1 rounded-lg border border-accent bg-bg-surface px-2 py-1 text-sm text-text-primary outline-none ring-0 focus:ring-2 focus:ring-accent/40"/><button type="button" aria-label="保存会话名称" disabled={saving} onMouseDown={e => e.preventDefault()} onClick={() => void save()} className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-accent disabled:opacity-50"><Check size={16}/></button><button type="button" aria-label="取消重命名" disabled={saving} onMouseDown={e => e.preventDefault()} onClick={cancel} className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-text-muted"><X size={16}/></button></div>{error && <p role="alert" aria-live="polite" className="mt-1 text-xs text-red-500">{error}</p>}</div>;
}
